name: emscripten

on:
  push:
    branches: [ "unity" ]
  pull_request:
    branches: [ "unity" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: Emscripten (wasm32)
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - uses: mymindstorm/setup-emsdk@v14
      with:
        version: 3.1.8

    - name: Configure CMake
      run: emcmake cmake -S . -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build build --config ${{env.BUILD_TYPE}}

    - name: Install
      run: cmake --install build --config ${{env.BUILD_TYPE}} --prefix dist

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: emscripten-wasm
        path: dist
